data:
  name: 'VERIWild'
  pkl_path: '../outputs/veriwild.pkl'
  train_size: (256, 256)
  valid_size: (256, 256)
  train_num_workers: 16
  test_num_workers: 4
  batch_size: 128
  with_mask: True
  test_ext: '_3000'

loss:
  losses: ["id", "triplet", "center", "local-triplet"]

test:
  remove_junk: True
  lambda_: 0.5

device: 'cuda'
output_dir: '../outputs/veriwild_b128_pven/'

